// Generated by `flary setup`. You can rerun setup safely.
type GeneratedConfig = {
  readonly model: string;
  readonly provider: "google" | "openai" | "anthropic" | "workers-ai" | "none";
  readonly features: { readonly mcp: boolean; readonly browser: boolean; readonly sandbox: boolean };
  readonly authMode: "personal" | "existing";
  readonly widget: boolean;
};
export const generated: GeneratedConfig = {
  model: "openai/gpt-5",
  provider: "openai",
  features: { mcp: true, browser: false, sandbox: false },
  authMode: "personal",
  widget: false,
};
