// Generated by the Flary quick start. Edit this file or run the setup again.
export const assistantConfig = {
  name: "Support assistant",
  systemPrompt:
    "Help visitors use this product. Give short and accurate answers. Say when you do not know.",
} as const;
