// Generated by `flary setup`. You can rerun setup safely.
type GeneratedConfig = {
  readonly model: string;
  readonly provider: "openai" | "anthropic" | "workers-ai" | "none";
  readonly features: { readonly mcp: boolean; readonly browser: boolean; readonly sandbox: boolean };
  readonly authMode: "personal" | "existing";
};
export const generated: GeneratedConfig = {
  model: "openai/gpt-5",
  provider: "openai",
  features: { mcp: false, browser: false, sandbox: false },
  authMode: "existing",
};
