import * as React from "react";

/** Small, token-driven defaults. Product apps can override every class. */
export const flaryReactStyles = `
.flary-markdown{overflow-wrap:anywhere}.flary-markdown>*:first-child{margin-top:0}.flary-markdown>*:last-child{margin-bottom:0}.flary-markdown p{margin:.55em 0}.flary-markdown ul,.flary-markdown ol{margin:.55em 0;padding-left:1.35em}.flary-markdown li+li{margin-top:.28em}.flary-markdown a{color:var(--flary-accent,#1769e0);font-weight:650;text-underline-offset:3px}.flary-markdown pre{max-width:100%;overflow:auto;border:1px solid var(--flary-line,#d9dde1);border-radius:10px;background:var(--flary-code,#f7f8f9);padding:12px}.flary-markdown code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.flary-markdown table{display:block;max-width:100%;overflow:auto;border-collapse:collapse}.flary-markdown th,.flary-markdown td{border-bottom:1px solid var(--flary-line,#d9dde1);padding:7px 9px;text-align:left}
.flary-artifact{margin:12px 0;overflow:hidden;border:1px solid var(--flary-line,#d9dde1);border-radius:14px;background:var(--flary-panel,#fff)}.flary-artifact__header{display:flex;align-items:center;min-height:40px;padding:8px 12px;border-bottom:1px solid var(--flary-line,#d9dde1);font-size:12px;font-weight:700}.flary-artifact__frame{display:block;width:100%;height:var(--flary-artifact-height);border:0;background:white}
.flary-user-input{display:grid;gap:12px;margin:12px 0;padding:14px;border:1px solid var(--flary-line,#d9dde1);border-radius:14px;background:var(--flary-panel,#fff)}.flary-user-input fieldset{min-width:0;margin:0;padding:0;border:0}.flary-user-input legend{display:grid;gap:3px;margin-bottom:9px}.flary-user-input legend span{color:var(--flary-muted,#687078);font-size:10px;font-weight:750;letter-spacing:.08em;text-transform:uppercase}.flary-user-input__options{display:grid;gap:7px}.flary-user-input__options>label{display:flex;gap:9px;align-items:flex-start;padding:9px;border:1px solid var(--flary-line,#d9dde1);border-radius:10px;cursor:pointer}.flary-user-input__options strong,.flary-user-input__options small{display:block}.flary-user-input__options small{margin-top:2px;color:var(--flary-muted,#687078)}.flary-user-input__other{display:grid!important}.flary-user-input__other-label{font-size:11px;font-weight:700}.flary-user-input__other input{width:100%;min-height:38px;border:1px solid var(--flary-line,#d9dde1);border-radius:8px;padding:7px 9px;font:inherit}.flary-user-input>button{justify-self:start;min-height:38px;border:0;border-radius:9px;background:var(--flary-accent,#1769e0);color:white;padding:8px 14px;font:inherit;font-weight:700;cursor:pointer}.flary-user-input :focus-visible{outline:3px solid color-mix(in srgb,var(--flary-accent,#1769e0) 28%,transparent);outline-offset:2px}.flary-secret-input{display:grid;gap:10px;margin:12px 0;padding:14px;border:1px solid var(--flary-line,#d9dde1);border-radius:14px;background:var(--flary-panel,#fff)}.flary-secret-input label{display:grid;gap:5px}.flary-secret-input label span{color:var(--flary-muted,#687078);font-size:12px}.flary-secret-input input{min-height:40px;border:1px solid var(--flary-line,#d9dde1);border-radius:8px;padding:8px 10px;font:inherit}.flary-secret-input button{justify-self:start;min-height:38px;border:0;border-radius:9px;background:var(--flary-accent,#1769e0);color:#fff;padding:8px 14px;font:inherit;font-weight:700}.flary-secret-input-required p{margin:0;color:var(--flary-muted,#687078)}@media(prefers-reduced-motion:reduce){.flary-markdown *{animation:none!important;transition:none!important}}
`;

export function FlaryReactStyles() {
  return <style data-flary-react-styles="">{flaryReactStyles}</style>;
}
